//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by SystemInfo.rc
//
#define IDD_SYSTEMINFO_DIALOG           102
#define IDR_MAINFRAME                   128
#define IDR_241                         129
#define IDD_SYSINFO_DIALOG              133
#define IDD_CPUINFO_DIALOG              133
#define IDD_MONITORING_DIALOG           134
#define IDB_BITMAP1                     136
#define IDB_BITMAP2                     137
#define IDB_EVGA_LOGO_1                 195
#define IDB_EVGA_LOGO_2                 197
#define IDD_SPD_DIALOG                  200
#define IDD_MEMORY_DIALOG               201
#define IDD_DISPLAY_DIALOG              203
#define IDB_INTEL                       204
#define IDB_INTEL_COREI7                206
#define IDB_INTEL_COREI5                207
#define IDB_INTEL_COREI3                208
#define IDB_INTEL_P2                    209
#define IDB_INTEL_P3                    210
#define IDB_INTEL_P3_M                  211
#define IDB_INTEL_PENTIUM_M             212
#define IDB_INTEL_P4                    213
#define IDB_INTEL_CORE2_DUO             214
#define IDB_INTEL_ATOM                  215
#define IDB_AMD                         216
#define IDB_BITMAP4                     217
#define IDB_AMD_K6                      217
#define IDB_INTEL_P4_EE                 218
#define IDB_INTEL_P4_HT                 219
#define IDB_INTEL_P4_M                  220
#define IDB_INTEL_PENTIUM_XE            221
#define IDB_INTEL_XEON                  222
#define IDB_INTEL_CELERON_D             223
#define IDB_INTEL_CELERON_M             225
#define IDB_INTEL_CELERON               226
#define IDB_INTEL_COREI7_EE             227
#define IDB_INTEL_ITANIUM               228
#define IDB_INTEL_PENTIUM_D             230
#define IDB_INTEL_CORE_DUO              231
#define IDB_INTEL_CORE_SOLO             232
#define IDB_INTEL_CORE2_SOLO            233
#define IDB_INTEL_CORE2_QUAD            234
#define IDB_INTEL_CORE2_PENTIUM         235
#define IDB_INTEL_CORE2_EE              236
#define IDB_AMD_K6_2                    237
#define IDB_AMD_K6_3                    238
#define IDB_AMD_ATHLON                  239
#define IDB_AMD_ATHLON_XP               240
#define IDB_AMD_ATHLON64_FX             241
#define IDB_AMD_OPTERON                 242
#define IDB_VIA                         243
#define IDB_VIA_C3                      244
#define IDB_AMD_ATHLON_MP               245
#define IDB_AMD_ATHLON64                246
#define IDB_AMD_ATHLON64_M              247
#define IDB_AMD_DURON                   248
#define IDB_AMD_SEMPRON                 249
#define IDB_AMD_SEMPRON_K10             250
#define IDB_AMD_SEMPRON_M               251
#define IDB_AMD_TURION64                252
#define IDB_AMD_TURION64_X2             253
#define IDB_AMD_ATHLON64_X2             254
#define IDB_AMD_PHENOM                  256
#define IDB_VIA_C7                      257
#define IDB_VIA_C7_M                    258
#define IDB_AMD_PHENOM_X3               259
#define IDB_AMD_PHENOM2                 260
#define IDB_AMD_PHENOM2_X2              261
#define IDB_AMD_ATHLON2_X2              262
#define IDB_AMD_ATHLON2                 263
#define IDB_AMD_PHENOM_FX               264
#define IDB_AMD_TURION64_K10            265
#define IDB_AMD_TURION64_ULTRA          266
#define IDB_VIA_EDEN                    267
#define IDB_CYRIX                       269
#define IDB_BITMAP3                     270
#define IDB_VIA_NANO                    270
#define IDB_AMD_PHENOM2_X4              271
#define IDB_BITMAP5                     272
#define IDB_AMD_PHENOM2_X6              272
#define IDR_242                         273
#define IDB_INTEL_PENTIUM               274
#define IDB_INTEL_COREI7_V2             275
#define IDB_INTEL_COREI7XE_V2           276
#define IDB_INTEL_COREI5_V2             277
#define IDB_INTEL_COREI3_V2             278
#define IDB_INTEL_XEON_V2               279
#define IDB_AMD_ATHLON_NEO              280
#define IDB_AMD_ATHLON_K10              281
#define IDB_VIA_C7_D                    283
#define IDB_BITMAP6                     284
#define IDB_TRANSMETA_EFFICEON          284
#define IDB_INTEL_COREI7_V4             285
#define IDB_INTEL_COREI5_V4             286
#define IDB_INTEL_COREI3_V4             287
#define IDB_VIA_EDEN_X2                 287
#define IDB_INTEL_XEON_V4               288
#define IDB_INTEL_PENTIUM_V4            289
#define IDB_AMD_VISION                  290
#define IDB_AMD_K15_OPTERON             291
#define IDB_AMD_OPTERON_K10             292
#define IDB_AMD_K15_A10T                293
#define IDB_AMD_K15_A10R                294
#define IDB_AMD_K15_A8R                 295
#define IDB_AMD_ATHLON_X4_K15           296
#define IDB_AMD_K15_FXB                 297
#define IDB_AMD_K15_FXV                 298
#define IDB_AMD_K16_A6K                 299
#define IDB_AMD_K16_A4K                 300
#define IDB_VIA_WINCHIP                 301
#define IDB_VIA_NANO_X2                 302
#define IDB_VIA_QUADCORE                304
#define IDB_INTEL_ATOM_V2               308
#define IDB_INTEL_ATOM_V4               309
#define IDB_INTEL_P1                    310
#define IDB_INTEL_P1MMX                 311
#define IDB_EMPTY                       312
#define IDB_INTEL_PPRO                  313
#define IDB_INTEL_CELERON_V4            314
#define IDB_AMD_K16_OPTERON             315
#define IDB_AMD_K16_ATHLON              316
#define IDB_BITMAP7                     317
#define IDB_AMD_K16_SEMPRON             317
#define IDC_COMBO1                      1000
#define IDC_COMBO_PLL                   1000
#define IDC_COMBO_PROC_SEL              1000
#define IDC_VCO                         1002
#define IDC_STATIC_RAM_TYPE             1002
#define IDC_SELECTED_VCO                1003
#define IDC_STATIC_RAM_SIZE             1004
#define IDC_GPU_NAME                    1004
#define IDC_VCO2                        1005
#define IDC_SPREAD_STATUS               1005
#define IDC_MAIN_TAB                    1005
#define IDC_STATIC_RAM_CHANNELS         1005
#define IDC_GPU_CODENAME                1005
#define IDC_STATIC_RAM_FREQUENCY        1006
#define IDC_GPU_PROCESS                 1006
#define IDC_STATIC_RAM_CAS_L            1007
#define IDC_GPU_PCI_ID                  1007
#define IDC_GPU_PCI_SUBID               1008
#define IDC_STATIC_RAM_RTOC             1009
#define IDC_LABEL_GPU_NAME              1011
#define IDC_STATIC_SPD_MANUFACTURER     1012
#define IDC_STATIC_RAM_RPRE             1012
#define IDC_LABEL_GPU_CODENAME          1012
#define IDC_BUTTON1                     1013
#define IDC_BUTTON_OK                   1013
#define IDC_STATIC_SPD_FREQUENCY        1013
#define IDC_LABEL_GPU_PCI_ID            1013
#define IDC_STATIC_SPD_CAS              1014
#define IDC_STATIC_RAM_TRAS             1014
#define IDC_LABEL_GPU_PROCESS           1014
#define IDC_STATIC_SPD_RASTOCAS         1015
#define IDC_LABEL_GPU_PCI_SUBID         1015
#define IDC_STATIC_SPD_RASPRECHARGE     1016
#define IDC_STATIC_RAM_TRC              1016
#define IDC_STATIC_SPD_TRAS             1017
#define IDC_STATIC_SPD_TRC              1018
#define IDC_PLLOUTPUT_CPU10             1019
#define IDC_STATIC_SPD_BANDWIDTH        1019
#define IDC_STATIC_RAM_COMMAND_RATE     1019
#define IDC_BUTTON2                     1020
#define IDC_STATIC_SPD_PARTNUMBER       1020
#define IDC_BUTTON3                     1021
#define IDC_EVGA_LOGO                   1021
#define IDC_STATIC_SPD_SERIALNUMBER     1021
#define IDC_STATIC_SPD_SIZE             1022
#define IDC_STATIC_SPD_CORRECTION       1023
#define IDC_COMBO_PROCESSOR2            1024
#define IDC_STATIC_SPD_BUFFERED         1024
#define IDC_APPLY_BUTTON2               1025
#define IDC_BUTTON4                     1025
#define IDC_STATIC_SPD_DATE             1025
#define IDC_LABEL_CORE_8                1026
#define IDC_STATIC_SPD_REGISTERED       1026
#define IDC_CORE_4                      1027
#define IDC_LABEL_CORE_9                1027
#define IDC_STATIC_SPD_EXT              1027
#define IDC_CORE_5                      1028
#define IDC_LABEL_CORE_10               1028
#define IDC_STATIC_SPD_CR               1028
#define IDC_CORE_6                      1029
#define IDC_CORE_M_4                    1029
#define IDC_STATIC_SPD_VDD              1029
#define IDC_CORE_7                      1030
#define IDC_CORE_M_5                    1030
#define IDC_CORE_M_6                    1031
#define IDC_CORE_M_7                    1032
#define IDC_LABEL_CORE_11               1033
#define IDC_COMBO_OUTPUT_1              1033
#define IDC_COMBO_OUTPUT_2              1035
#define IDC_STATIC_VOLTAGE_1            1036
#define IDC_VOLTAGE_1                   1037
#define IDC_COMBO_OUTPUT_3              1037
#define IDC_CPU1_CORE_STEPPING          1038
#define IDC_VOLTAGE_2                   1038
#define IDC_LABEL_OUTPUT_3              1038
#define IDC_STATIC_VOLTAGE_2            1039
#define IDC_COMBO_OUTPUT_4              1039
#define IDC_VOLTAGE_3                   1040
#define IDC_LABEL_OUTPUT_4              1040
#define IDC_STATIC_VOLTAGE_3            1041
#define IDC_COMBO_OUTPUT_5              1041
#define IDC_VOLTAGE_4                   1042
#define IDC_LABEL_OUTPUT_5              1042
#define IDC_STATIC_VOLTAGE_4            1043
#define IDC_COMBO_OUTPUT_6              1043
#define IDC_VOLTAGE_5                   1044
#define IDC_LABEL_OUTPUT_6              1044
#define IDC_STATIC_VOLTAGE_5            1045
#define IDC_COMBO_OUTPUT_7              1045
#define IDC_VOLTAGE_6                   1046
#define IDC_LABEL_OUTPUT_7              1046
#define IDC_STATIC_VOLTAGE_6            1047
#define IDC_COMBO_OUTPUT_8              1047
#define IDC_VOLTAGE_7                   1048
#define IDC_LABEL_OUTPUT_8              1048
#define IDC_STATIC_VOLTAGE_7            1049
#define IDC_COMBO_OUTPUT_9              1049
#define IDC_VOLTAGE_8                   1050
#define IDC_LABEL_OUTPUT_9              1050
#define IDC_BUTTON_APPLY                1051
#define IDC_STATIC_VOLTAGE_8            1051
#define IDC_BUTTON_MICROCONTROLLER_APPLY 1051
#define IDC_VOLTAGE_9                   1052
#define IDC_COMBO_OUTPUT_10             1052
#define IDC_STATIC_VOLTAGE_9            1053
#define IDC_LABEL_OUTPUT_10             1053
#define IDC_TEMPERATURE_1               1054
#define IDC_COMBO_OUTPUT_11             1054
#define IDC_STATIC_TEMPERATURE_1        1055
#define IDC_LABEL_OUTPUT_11             1055
#define IDC_TEMPERATURE_2               1056
#define IDC_RAM_TYPE                    1056
#define IDC_STATIC_TEMPERATURE_2        1057
#define IDC_STATIC_DISPLAY_GENERAL      1057
#define IDC_TEMPERATURE_3               1058
#define IDC_SPD_MANUFACTURER            1058
#define IDC_COMBO_DISPLAY               1058
#define IDC_STATIC_TEMPERATURE_3        1059
#define IDC_SPD_FREQUENCY0              1059
#define IDC_STATIC_DISPLAY_CODENAME     1059
#define IDC_TEMPERATURE_4               1060
#define IDC_SPD_CAS0                    1060
#define IDC_STATIC_TEMPERATURE_4        1061
#define IDC_SPD_RASTOCAS0               1061
#define IDC_RAM_SIZE                    1061
#define IDC_COMBO_PERFLEVEL             1061
#define IDC_TEMPERATURE_5               1062
#define IDC_SPD_RASPRECHARGE0           1062
#define IDC_STATIC_DISPLAY_PERFLEVEL    1062
#define IDC_STATIC_TEMPERATURE_5        1063
#define IDC_SPD_TRAS0                   1063
#define IDC_TEMPERATURE_C1              1064
#define IDC_SPD_FREQUENCY1              1064
#define IDC_RAM_FREQUENCY               1064
#define IDC_SLIDER_CORE                 1064
#define IDC_CPU1_CLOCK                  1065
#define IDC_STATIC_TEMPERATURE_C1       1065
#define IDC_SPD_CAS1                    1065
#define IDC_CORE_CLOCK_CURRENT          1065
#define IDC_TEMPERATURE_C2              1066
#define IDC_SPD_RASTOCAS1               1066
#define IDC_VRAM_SIZE                   1066
#define IDC_STATIC_TEMPERATURE_C2       1067
#define IDC_SPD_RASPRECHARGE1           1067
#define IDC_RAM_CAS_LATENCY             1067
#define IDC_TEMPERATURE_C3              1068
#define IDC_SPD_TRAS1                   1068
#define IDC_RAM_CHANNELS                1068
#define IDC_STATIC_TEMPERATURE_C3       1069
#define IDC_SPD_FREQUENCY2              1069
#define IDC_SHADERS_CLOCK_CURRENT       1069
#define IDC_TEMPERATURE_C4              1070
#define IDC_SPD_CAS2                    1070
#define IDC_RAM_RAS_TO_CAS              1070
#define IDC_MEMORY_CLOCK_CURRENT        1070
#define IDC_CPU1_NAME                   1071
#define IDC_STATIC_TEMPERATURE_C4       1071
#define IDC_SPD_RASTOCAS2               1071
#define IDC_CORE_CLOCK_SEL              1071
#define IDC_SPD_RASPRECHARGE2           1072
#define IDC_SHADERS_CLOCK_SEL           1072
#define IDC_TEMPERATURE_C5              1072
#define IDC_SPD_TRAS2                   1073
#define IDC_RAM_RAS_PRECHARGE           1073
#define IDC_MEMORY_CLOCK_SEL            1073
#define IDC_STATIC_TEMPERATURE_C5       1073
#define IDC_SPD_FREQUENCY3              1074
#define IDC_STATIC_CORE                 1074
#define IDC_TEMPERATURE_C6              1074
#define IDC_SPD_BANDWIDTH               1075
#define IDC_STATIC_SHADERS              1075
#define IDC_STATIC_TEMPERATURE_C6       1075
#define IDC_FAN_1                       1076
#define IDC_SPD_PARTNUMBER              1076
#define IDC_RAM_TRAS                    1076
#define IDC_STATIC_FAN_1                1077
#define IDC_SPD_SERIALNUMBER            1077
#define IDC_STATIC_MMORY                1077
#define IDC_FAN_2                       1078
#define IDC_SPD_SIZE                    1078
#define IDC_STATIC_CURRENT              1078
#define IDC_STATIC_FAN_2                1079
#define IDC_SPD_CORRECTION              1079
#define IDC_RAM_TRC                     1079
#define IDC_STATIC_SELECTION            1079
#define IDC_CPU1_VENDOR                 1080
#define IDC_FAN_3                       1080
#define IDC_SPD_BUFFERED                1080
#define IDC_STATIC_CORE_SEL             1080
#define IDC_STATIC_FAN_3                1081
#define IDC_SPD_DATE                    1081
#define IDC_SLIDER_SHADERS              1081
#define IDC_FAN_4                       1082
#define IDC_SPD_REGISTERED              1082
#define IDC_STATIC_SHADERS_SEL          1082
#define IDC_STATIC_FAN_4                1083
#define IDC_SPD_EXT                     1083
#define IDC_RAM_COMMAND_RATE            1083
#define IDC_SLIDER_MEMORY               1083
#define IDC_VOLTAGE_10                  1084
#define IDC_SPD_CAS3                    1084
#define IDC_STATIC_MEMORY_SEL           1084
#define IDC_CPU1_FAMILY                 1085
#define IDC_STATIC_VOLTAGE_10           1085
#define IDC_SPD_RASTOCAS3               1085
#define IDC_CPU1_EXTFAMILY              1086
#define IDC_SPD_RASPRECHARGE3           1086
#define IDC_SPD_TRAS3                   1087
#define IDC_SPD_TRC1                    1088
#define IDC_SPD_TRC2                    1089
#define IDC_CPU1_MODEL                  1090
#define IDC_SPD_TRC3                    1090
#define IDC_CPU1_EXTMODEL               1091
#define IDC_SPD_TRC0                    1091
#define IDC_SPD_CR1                     1092
#define IDC_SPD_CR2                     1093
#define IDC_SPD_CR3                     1094
#define IDC_SPD_CR0                     1095
#define IDC_CPU1_STEPPING               1096
#define IDC_SPD_VDD1                    1096
#define IDC_SPD_VDD2                    1097
#define IDC_SPD_VDD3                    1098
#define IDC_SPD_PROFILE_NAME0           1099
#define IDC_SPD_PROFILE_NAME1           1100
#define IDC_SPD_PROFILE_NAME2           1101
#define IDC_CPU1_BRAND_ID               1102
#define IDC_SPD_PROFILE_NAME3           1102
#define IDC_CPU1_TDP                    1102
#define IDC_CPU1_PACKAGE                1108
#define IDC_CPU1_PROCESS                1110
#define IDC_CPU1_CLOCK_MULTIPLIER       1112
#define IDC_CPU1_FSB_FREQUENCY          1113
#define IDC_CPU1_L1_D_SIZE              1114
#define IDC_VRAM_TYPE                   1114
#define IDC_VRAM_BUS_WIDTH              1115
#define IDC_CPU1_L1_D_ASSO              1115
#define IDC_CPU1_L2_SIZE                1116
#define IDC_CPU1_BUS_FREQUENCY          1117
#define IDC_CPU1_L3_SIZE                1118
#define IDC_CPU1_NBTHREADS              1119
#define IDC_CPU1_NBCORES                1120
#define IDC_CPU1_L1_I_SIZE2             1121
#define IDC_CPU1_L1_I_SIZE              1121
#define IDC_CPU1_CORE_VOLTAGE           1122
#define IDC_STATIC_L2_SIZE              1123
#define IDC_STATIC_L3_SIZE              1124
#define IDC_CPU1_L1_I_ASSO              1125
#define IDC_CPU1_L2_ASSO                1126
#define IDC_CPU1_L3_ASSO                1127
#define IDC_STATIC_CORE_STEPPING        1129
#define IDC_STATIC_CLOCK_MUL            1130
#define IDC_STATIC_FSB_FREQ             1131
#define IDC_SPD_VDD0                    1131
#define IDC_STATIC_PROCESS              1132
#define IDC_LABEL_VRAM_TYPE             1133
#define IDC_STATIC_BUS_SPEED            1134
#define IDC_LABEL_VRAM_BUS_WIDTH        1134
#define IDC_STATIC_CPU_SELECTION        1136
#define IDC_STATIC_PACKAGE              1143
#define IDC_STATIC_CPU_NAME             1148
#define IDC_STATIC_CPU_L1_D_SIZE        1152
#define IDC_STATIC_CPU_L1_I_SIZE        1153
#define IDC_STATIC_CPU_NBCORES          1154
#define IDC_STATIC_CORE_VOLTAGE         1155
#define IDC_STATIC_CPU_NBTHREADS        1156
#define IDC_STATIC_BRAND_ID             1166
#define IDC_STATIC_TDP                  1166
#define IDC_STATIC_MEMORY_TIMINGS       1175
#define IDC_STATIC_MEMORY_GENERAL       1177
#define IDC_CPU1_NAMESTRING             1185
#define IDC_STATIC_CPU_NAMESTRING       1187
#define IDC_CPU1_ISET                   1190
#define IDC_STATIC_CPU_CODENAME         1193
#define IDC_COMBO_SPD                   1196
#define IDC_CPU_LOGO                    1198
#define IDC_COMBO_CPUSEL                1199
#define IDC_STATIC_GROUP_PROCESSOR      1207
#define IDC_STATIC_GROUP_CLOCKS         1208
#define IDC_STATIC_GROUP_CACHE          1209
#define IDC_STATIC_GROUP_CLOCKS2        1209
#define IDC_STATIC_CPU_FAMILY           1210
#define IDC_STATIC_CPU_MODEL            1211
#define IDC_STATIC_CPU_STEPPING         1212
#define IDC_STATIC_CPU_EFAMILY          1213
#define IDC_STATIC_CPU_EMODEL           1214
#define IDC_STATIC_CPU_INSTRUCTIONS     1215
#define IDC_STATIC_CPU_SPEED            1216
#define IDC_LABEL_VRAM_SIZE             1217
#define IDC_STATIC_GROUP_GENERAL        1219
#define IDC_STATIC_TIMINGSTABLE         1231
#define IDC_RAM_TYPE_2                  1232
#define ID_POPUP_SAVEPLLSDUMP           32771
#define ID_POPUP2_LINKSLIDERS           32774

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        318
#define _APS_NEXT_COMMAND_VALUE         32776
#define _APS_NEXT_CONTROL_VALUE         1061
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
